#!/usr/bin/env bash

DATE=$(date +'%d-%m-%Y')

if [ ! -d "../../home/ubuntu/Janus/data/backups/" ]
then
  mkdir  "../../home/ubuntu/Janus/data/backups/"
fi

if [ ! -d "../../home/ubuntu/Janus/data/backups/$DATE" ]
then
  mkdir  "../../home/ubuntu/Janus/data/backups/$DATE"
fi



sudo zip -r "../../home/ubuntu/Janus/data/backups/$DATE/FULLBACKUP" ../../home/ubuntu/Janus/* -x "../../home/ubuntu/Janus/data/clipping"
